### ISSUE TITLE
Changing the UI of home page

### ISSUE THREAD

**Issue by tharanithar-r** [iriteshmishra/Open-Source-Organization#30]
Hello. I think the website has useful information but the website UI not looks good. I am interested in changing the UI to some card based style with logo like the below attached image. Kindly assign this to me. Thank you.

![Screenshot 2023-10-12 213650](https://github.com/iriteshmishra/Open-Source-Organization/assets/145109919/0e1dbca4-21e2-4bd3-8887-f825a683c672)

**Comment by priyamaggarwal18** [comment]
Hello @tharanithar-r, I think I can work on improving the CSS of this page and make the page more eye catching. So please assign this issue to me and label this issue as hacktoberfest2023.

**Comment by iriteshmishra** [comment]
I am assigned to both of you. Don't forget to tell the details about what are the changes you have made, create a screen recording too, after your added feat how the website is gonna look.
