### ISSUE TITLE
Improve the UI and add important card elements

### ISSUE THREAD

**Issue by Acesif** [iriteshmishra/Open-Source-Organization#53]
I think it would be pretty if the entries could be changed into a card view as mentioned in #8 point number 2.
Image below for reference
![image](https://github.com/iriteshmishra/Open-Source-Organization/assets/36653429/a902dd31-d5aa-4c13-9679-4cd6c411b40a)
I would also like to include necessary elements such as Deadline, Difficulty etc based on the information found each of those websites. 
Please assign me to the task if you think this is a good issue

**Comment by iriteshmishra** [comment]
I am assigned to both of you. Don't forget to tell the details about what are the changes you have made, create a screen recording too, after your added feat how the website is gonna look.

**Comment by Acesif** [comment]
@iriteshmishra I do not have write access

**Comment by iriteshmishra** [comment]
Any update @Acesif

**Comment by Acesif** [comment]
> Any update @Acesif 

Please check PR #64

**Comment by iriteshmishra** [comment]
RESOLVE CONFLICT

**Comment by Acesif** [comment]
Due to the merging of the latest PR, #64 is no longer valid, I'll close it and make another PR that works with the current version.
