### ISSUE TITLE
Add new Open Source Organization

### ISSUE THREAD

**Issue by JayOaks** [iriteshmishra/Open-Source-Organization#75]
Hello,

I want to add an open source organization that is not on the current list.

Its name is [{all in}](https://allinopensource.org/). All In is an organization dedicated to promoting inclusivity, diversity and equity in open source. They have 2 programs:
- All In Students Program
- All In Africa Program

**Comment by iriteshmishra** [comment]
Go for it. @JayOaks  👍

**Comment by JayOaks** [comment]
Thank you.

Can I search for more and keep adding to the list?

**Comment by iriteshmishra** [comment]
@JayOaks Yes obviously, I will never deny. Keep contributing as much as you want. If you like this repo then do mark as a star.

**Comment by JayOaks** [comment]
Will do.
Thanks.
