### ISSUE TITLE
Improve Code Structure

### ISSUE THREAD

**Issue by harshal255** [iriteshmishra/Open-Source-Organization#8]
1. make a JSON file for the open source organization & use the es6+ method (like a map for displaying all open source organization details in index.js).
2.  add a logo as well for particular open-source organizations
3. use grid & pagination for awesome user interface
4.  improve read.md file related to task 1
- so, the user can easily put data in json file instead of doing this hard coding.

**Comment by iriteshmishra** [comment]
Thanks 🤝 @harshal255 . I was thinking about the same for points 2 and 3. I am definitely going to work on all the points you have mentioned above.

**Comment by harshal255** [comment]
Yeahh great🫡

**Comment by harshal255** [comment]
> Thanks 🤝 @harshal255 . I was thinking about the same for points 2 and 3. I am definitely going to work on all the points you have mentioned above.

Do you want to add a good read.md file??

**Comment by iriteshmishra** [comment]
> > Thanks 🤝 @harshal255 . I was thinking about the same for points 2 and 3. I am definitely going to work on all the points you have mentioned above.
> 
> Do you want to add a good read.md file??

Yes, You can go ahead 👍

**Comment by harshal255** [comment]
okay brother 🤝💯

**Comment by iriteshmishra** [comment]
#9 Merged
