### ISSUE TITLE
Implementing Json data to show the organization 

### ISSUE THREAD

**Issue by tharanithar-r** [iriteshmishra/Open-Source-Organization#80]
Currently the organization are hard coded but we can create a Json data and Dynamically show the organization. I am interested in working on this. Kindly assign this to me.

**Comment by tharanithar-r** [comment]
Can I start to work on this issue?

**Comment by iriteshmishra** [comment]
I thought to add this feat after hacktoberfest as most of the beginners might not understand where to make changes.  @tharanithar-r
